# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.InternalVideoListInternalVideoList.api.internal_video_list_api import InternalVideoListApi  # noqa: E501


class TestInternalVideoListApi(unittest.TestCase):
    """InternalVideoListApi unit test stubs"""

    def setUp(self):
        self.api = InternalVideoListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_internal_video_list_get(self):
        """Test case for internal_video_list_get

        列出已发布的视频  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
