# coding: utf-8

"""
    团购活动下线

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponGrouponOffline.api.enterprise_groupon_offline_api import EnterpriseGrouponOfflineApi  # noqa: E501


class TestEnterpriseGrouponOfflineApi(unittest.TestCase):
    """EnterpriseGrouponOfflineApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponOfflineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_offline_post(self):
        """Test case for enterprise_groupon_offline_post

        团购活动下线  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
