# coding: utf-8

"""
    券码核销

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponCodeCodeVerification.api.enterprise_groupon_code_cert_api import EnterpriseGrouponCodeCertApi  # noqa: E501


class TestEnterpriseGrouponCodeCertApi(unittest.TestCase):
    """EnterpriseGrouponCodeCertApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponCodeCertApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_code_verification_post(self):
        """Test case for enterprise_groupon_code_verification_post

        券码核销  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
