# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.PoiProductProduct
from models.spu_attributes9101 import SpuAttributes9101  # noqa: E501
from douyin_open.PoiProductProduct.rest import ApiException


class TestSpuAttributes9101(unittest.TestCase):
    """SpuAttributes9101 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpuAttributes9101(self):
        """Test SpuAttributes9101"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.PoiProductProduct.models.spu_attributes9101.SpuAttributes9101()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
