# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ToutiaoOauth2Oauth2.api.toutiao_client_token_api import ToutiaoClientTokenApi  # noqa: E501


class TestToutiaoClientTokenApi(unittest.TestCase):
    """ToutiaoClientTokenApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoClientTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_client_token_get(self):
        """Test case for oauth_client_token_get

        生成client_token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
