# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.PoiOrderOrder
from models.poiexthotelordercommit_customer_list import PoiexthotelordercommitCustomerList  # noqa: E501
from douyin_open.PoiOrderOrder.rest import ApiException


class TestPoiexthotelordercommitCustomerList(unittest.TestCase):
    """PoiexthotelordercommitCustomerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoiexthotelordercommitCustomerList(self):
        """Test PoiexthotelordercommitCustomerList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.PoiOrderOrder.models.poiexthotelordercommit_customer_list.PoiexthotelordercommitCustomerList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
