# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.PoiOrderOrder.api.poi_order_api import PoiOrderApi  # noqa: E501


class TestPoiOrderApi(unittest.TestCase):
    """PoiOrderApi unit test stubs"""

    def setUp(self):
        self.api = PoiOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_poi_ext_hotel_order_cancel_post(self):
        """Test case for poi_ext_hotel_order_cancel_post

        取消订单(该接口由接入方实现)  # noqa: E501
        """
        pass

    def test_poi_ext_hotel_order_commit_post(self):
        """Test case for poi_ext_hotel_order_commit_post

        下单接口(该接口由接入方实现)  # noqa: E501
        """
        pass

    def test_poi_ext_hotel_order_status_post(self):
        """Test case for poi_ext_hotel_order_status_post

        支付状态通知(该接口由接入方实现)  # noqa: E501
        """
        pass

    def test_poi_order_status_post(self):
        """Test case for poi_order_status_post

        订单状态同步接口  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
