# coding: utf-8

"""

    通过西瓜视频id批量获取已分享视频数据信息  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.XiguaDataVideoData.api.xigua_video_data_api import XiguaVideoDataApi  # noqa: E501


class TestXiguaVideoDataApi(unittest.TestCase):
    """XiguaVideoDataApi unit test stubs"""

    def setUp(self):
        self.api = XiguaVideoDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_xigua_video_data_post(self):
        """Test case for xigua_video_data_post

        查询特定视频的视频数据  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
