# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.Oauth2SilentLogin.api.authorize_v2_api import AuthorizeV2Api  # noqa: E501


class TestAuthorizeV2Api(unittest.TestCase):
    """AuthorizeV2Api unit test stubs"""

    def setUp(self):
        self.api = AuthorizeV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_authorize_v2_get(self):
        """Test case for oauth_authorize_v2_get

        获取授权码(code)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
