# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.PoiSupplierSupplier
from models.hotel_service_facility import HotelServiceFacility  # noqa: E501
from douyin_open.PoiSupplierSupplier.rest import ApiException


class TestHotelServiceFacility(unittest.TestCase):
    """HotelServiceFacility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHotelServiceFacility(self):
        """Test HotelServiceFacility"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.PoiSupplierSupplier.models.hotel_service_facility.HotelServiceFacility()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
