# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.Oauth2UserToken.api.oauth_code_api import OauthCodeApi  # noqa: E501


class TestOauthCodeApi(unittest.TestCase):
    """OauthCodeApi unit test stubs"""

    def setUp(self):
        self.api = OauthCodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_platform_oauth_connect_get(self):
        """Test case for platform_oauth_connect_get

        获取授权码(code)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
