# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.UserFansFans.api.fans_list_api import FansListApi  # noqa: E501


class TestFansListApi(unittest.TestCase):
    """FansListApi unit test stubs"""

    def setUp(self):
        self.api = FansListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fans_list_get(self):
        """Test case for fans_list_get

        粉丝列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
