# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.VideoSearchVideoSearch
from models.search_video import SearchVideo  # noqa: E501
from douyin_open.VideoSearchVideoSearch.rest import ApiException


class TestSearchVideo(unittest.TestCase):
    """SearchVideo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchVideo(self):
        """Test SearchVideo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.VideoSearchVideoSearch.models.search_video.SearchVideo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
