# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ToutiaoVideoListVideoList.api.toutiao_video_list_api import ToutiaoVideoListApi  # noqa: E501


class TestToutiaoVideoListApi(unittest.TestCase):
    """ToutiaoVideoListApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoVideoListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_toutiao_video_list_get(self):
        """Test case for toutiao_video_list_get

        查询授权帐号的视频列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
