# coding: utf-8

"""
    团购活动订单汇总信息

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponOrderOrderOverview.api.enterprise_groupon_order_overview_api import EnterpriseGrouponOrderOverviewApi  # noqa: E501


class TestEnterpriseGrouponOrderOverviewApi(unittest.TestCase):
    """EnterpriseGrouponOrderOverviewApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponOrderOverviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_order_overview_get(self):
        """Test case for enterprise_groupon_order_overview_get

        团购活动订单汇总信息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
