# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ExternalDataPoiExternalDataPoi.api.data_external_poi_user_api import DataExternalPoiUserApi  # noqa: E501


class TestDataExternalPoiUserApi(unittest.TestCase):
    """DataExternalPoiUserApi unit test stubs"""

    def setUp(self):
        self.api = DataExternalPoiUserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_external_poi_user_get(self):
        """Test case for data_external_poi_user_get

        POI用户数据  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
