# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ExternalDataPoiExternalDataPoi.api.data_external_poi_claim_list_api import DataExternalPoiClaimListApi  # noqa: E501


class TestDataExternalPoiClaimListApi(unittest.TestCase):
    """DataExternalPoiClaimListApi unit test stubs"""

    def setUp(self):
        self.api = DataExternalPoiClaimListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_external_poi_claim_list_get(self):
        """Test case for data_external_poi_claim_list_get

        POI认领列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
