# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.VideoPoiVideoPoi
from models.poi import Poi  # noqa: E501
from douyin_open.VideoPoiVideoPoi.rest import ApiException


class TestPoi(unittest.TestCase):
    """Poi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoi(self):
        """Test Poi"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.VideoPoiVideoPoi.models.poi.Poi()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
