# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.StarAuthorStarAuthor.api.star_author_score_api import StarAuthorScoreApi  # noqa: E501


class TestStarAuthorScoreApi(unittest.TestCase):
    """StarAuthorScoreApi unit test stubs"""

    def setUp(self):
        self.api = StarAuthorScoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_star_author_score_get(self):
        """Test case for star_author_score_get

        获取抖音星图达人指数  # noqa: E501
        """
        pass

    def test_star_author_score_v2_get(self):
        """Test case for star_author_score_v2_get

        获取抖音星图达人指数数据V2  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
