# coding: utf-8

"""

    通过头条视频id批量获取已分享视频数据信息  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ToutiaoVideoDataVideoData.api.toutiao_video_data_api import ToutiaoVideoDataApi  # noqa: E501


class TestToutiaoVideoDataApi(unittest.TestCase):
    """ToutiaoVideoDataApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoVideoDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_toutiao_video_data_post(self):
        """Test case for toutiao_video_data_post

        查询特定视频的视频信息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
