# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ExternalDataItemExternalDataItem.api.data_external_item_api import DataExternalItemApi  # noqa: E501


class TestDataExternalItemApi(unittest.TestCase):
    """DataExternalItemApi unit test stubs"""

    def setUp(self):
        self.api = DataExternalItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_external_item_base_get(self):
        """Test case for data_external_item_base_get

        获取视频基础数据  # noqa: E501
        """
        pass

    def test_data_external_item_comment_get(self):
        """Test case for data_external_item_comment_get

        获取视频评论数据  # noqa: E501
        """
        pass

    def test_data_external_item_like_get(self):
        """Test case for data_external_item_like_get

        获取视频点赞数据  # noqa: E501
        """
        pass

    def test_data_external_item_play_get(self):
        """Test case for data_external_item_play_get

        获取视频播放数据  # noqa: E501
        """
        pass

    def test_data_external_item_share_get(self):
        """Test case for data_external_item_share_get

        获取视频分享数据  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
