# coding: utf-8

"""
    团购活动事件回调

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseGrouponGrouponCommonGrouponEvent
from models.custom_code_fetch_response import CustomCodeFetchResponse  # noqa: E501
from douyin_open.EnterpriseGrouponGrouponCommonGrouponEvent.rest import ApiException


class TestCustomCodeFetchResponse(unittest.TestCase):
    """CustomCodeFetchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomCodeFetchResponse(self):
        """Test CustomCodeFetchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseGrouponGrouponCommonGrouponEvent.models.custom_code_fetch_response.CustomCodeFetchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
