# coding: utf-8

"""
    发送消息

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ImMsgSendImMsgSend.api.im_api import ImApi  # noqa: E501


class TestImApi(unittest.TestCase):
    """ImApi unit test stubs"""

    def setUp(self):
        self.api = ImApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_im_msg_send_post(self):
        """Test case for im_msg_send_post

        给抖音用户发送消息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
