# coding: utf-8

"""
    删除消息卡片

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseImFancyCardCardDelete.api.enterprise_im_fancy_card_del_api import EnterpriseImFancyCardDelApi  # noqa: E501


class TestEnterpriseImFancyCardDelApi(unittest.TestCase):
    """EnterpriseImFancyCardDelApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseImFancyCardDelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_im_fancy_card_delete_post(self):
        """Test case for enterprise_im_fancy_card_delete_post

        删除消息卡片  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
