# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.PoiSupplierSupplier
from models.supplier_attributes3101_preferential_policy import SupplierAttributes3101PreferentialPolicy  # noqa: E501
from douyin_open.PoiSupplierSupplier.rest import ApiException


class TestSupplierAttributes3101PreferentialPolicy(unittest.TestCase):
    """SupplierAttributes3101PreferentialPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupplierAttributes3101PreferentialPolicy(self):
        """Test SupplierAttributes3101PreferentialPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.PoiSupplierSupplier.models.supplier_attributes3101_preferential_policy.SupplierAttributes3101PreferentialPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
