# coding: utf-8

"""
    客服账号创建

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterprisePersonaPersonaCreate.api.enterprise_im_persona_create_api import EnterpriseImPersonaCreateApi  # noqa: E501


class TestEnterpriseImPersonaCreateApi(unittest.TestCase):
    """EnterpriseImPersonaCreateApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseImPersonaCreateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_im_persona_create_post(self):
        """Test case for enterprise_im_persona_create_post

        客服账号  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
