# coding: utf-8

"""

    通过头条视频id批量获取已分享视频数据信息  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ToutiaoVideoDataVideoData
from models.toutiao_video import ToutiaoVideo  # noqa: E501
from douyin_open.ToutiaoVideoDataVideoData.rest import ApiException


class TestToutiaoVideo(unittest.TestCase):
    """ToutiaoVideo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToutiaoVideo(self):
        """Test ToutiaoVideo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ToutiaoVideoDataVideoData.models.toutiao_video.ToutiaoVideo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
