# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ToutiaoOauth2Oauth2
from models.inline_response2001_data import InlineResponse2001Data  # noqa: E501
from douyin_open.ToutiaoOauth2Oauth2.rest import ApiException


class TestInlineResponse2001Data(unittest.TestCase):
    """InlineResponse2001Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Data(self):
        """Test InlineResponse2001Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ToutiaoOauth2Oauth2.models.inline_response2001_data.InlineResponse2001Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
