# coding: utf-8

"""

    获取用户的粉丝数据  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.FansDataFansData
from models.fans_data import FansData  # noqa: E501
from douyin_open.FansDataFansData.rest import ApiException


class TestFansData(unittest.TestCase):
    """FansData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFansData(self):
        """Test FansData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.FansDataFansData.models.fans_data.FansData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
