# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ExternalDataItemExternalDataItem
from models.external_item_play import ExternalItemPlay  # noqa: E501
from douyin_open.ExternalDataItemExternalDataItem.rest import ApiException


class TestExternalItemPlay(unittest.TestCase):
    """ExternalItemPlay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalItemPlay(self):
        """Test ExternalItemPlay"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ExternalDataItemExternalDataItem.models.external_item_play.ExternalItemPlay()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
