# coding: utf-8

"""
    自定义卷码预存

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponCodeCodeDeposit.api.enterprise_groupon_code_deposit_api import EnterpriseGrouponCodeDepositApi  # noqa: E501


class TestEnterpriseGrouponCodeDepositApi(unittest.TestCase):
    """EnterpriseGrouponCodeDepositApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponCodeDepositApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_code_deposit_post(self):
        """Test case for enterprise_groupon_code_deposit_post

        自定义卷码预存  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
