# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.VideoDeleteAwemeDelete.api.video_delete_api import VideoDeleteApi  # noqa: E501


class TestVideoDeleteApi(unittest.TestCase):
    """VideoDeleteApi unit test stubs"""

    def setUp(self):
        self.api = VideoDeleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_video_delete_post(self):
        """Test case for video_delete_post

        删除授权用户发布的视频  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
