# coding: utf-8

"""
    团购活动订单详情

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponOrderOrderDetail.api.enterprise_groupon_order_detail_api import EnterpriseGrouponOrderDetailApi  # noqa: E501


class TestEnterpriseGrouponOrderDetailApi(unittest.TestCase):
    """EnterpriseGrouponOrderDetailApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponOrderDetailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_order_detail_get(self):
        """Test case for enterprise_groupon_order_detail_get

        团购活动订单详情  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
