# coding: utf-8

"""
    团购活动列表

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponGrouponList.api.enterprise_groupon_list_api import EnterpriseGrouponListApi  # noqa: E501


class TestEnterpriseGrouponListApi(unittest.TestCase):
    """EnterpriseGrouponListApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_list_get(self):
        """Test case for enterprise_groupon_list_get

        团购活动列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
