# coding: utf-8

"""
    企业号发送消息

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseImEnterpriseIm.api.enterprise_im_msg_end_api import EnterpriseImMsgEndApi  # noqa: E501


class TestEnterpriseImMsgEndApi(unittest.TestCase):
    """EnterpriseImMsgEndApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseImMsgEndApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_im_message_send_post(self):
        """Test case for enterprise_im_message_send_post

        发送消息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
