# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.UserUserInfoUserInfo.api.user_info_api import UserInfoApi  # noqa: E501


class TestUserInfoApi(unittest.TestCase):
    """UserInfoApi unit test stubs"""

    def setUp(self):
        self.api = UserInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_userinfo_get(self):
        """Test case for oauth_userinfo_get

        获取用户信息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
