# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.HotsearchHotsearch.api.hotsearch_api import HotsearchApi  # noqa: E501


class TestHotsearchApi(unittest.TestCase):
    """HotsearchApi unit test stubs"""

    def setUp(self):
        self.api = HotsearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hotsearch_sentences_get(self):
        """Test case for hotsearch_sentences_get

        获取实时热点词  # noqa: E501
        """
        pass

    def test_hotsearch_trending_sentences_get(self):
        """Test case for hotsearch_trending_sentences_get

        获取上升词  # noqa: E501
        """
        pass

    def test_hotsearch_videos_get(self):
        """Test case for hotsearch_videos_get

        获取热点词聚合的视频  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
