# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.ToutiaoVideoCreateCreate.api.toutiao_video_publish_api import ToutiaoVideoPublishApi  # noqa: E501


class TestToutiaoVideoPublishApi(unittest.TestCase):
    """ToutiaoVideoPublishApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoVideoPublishApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_toutiao_video_create_post(self):
        """Test case for toutiao_video_create_post

        创建头条视频  # noqa: E501
        """
        pass

    def test_toutiao_video_part_complete_post(self):
        """Test case for toutiao_video_part_complete_post

        完成上传  # noqa: E501
        """
        pass

    def test_toutiao_video_part_init_post(self):
        """Test case for toutiao_video_part_init_post

        初始化上传  # noqa: E501
        """
        pass

    def test_toutiao_video_part_upload_post(self):
        """Test case for toutiao_video_part_upload_post

        上传视频分片到文件服务器  # noqa: E501
        """
        pass

    def test_toutiao_video_upload_post(self):
        """Test case for toutiao_video_upload_post

        上传视频到文件服务器  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
