# coding: utf-8

"""
    创建消息卡片

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseImCardCardSave
from models.h5 import H5  # noqa: E501
from douyin_open.EnterpriseImCardCardSave.rest import ApiException


class TestH5(unittest.TestCase):
    """H5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testH5(self):
        """Test H5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseImCardCardSave.models.h5.H5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
