# coding: utf-8

"""
    创建团购活动

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponGrouponSave.api.enterprise_groupon_save_api import EnterpriseGrouponSaveApi  # noqa: E501


class TestEnterpriseGrouponSaveApi(unittest.TestCase):
    """EnterpriseGrouponSaveApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponSaveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_save_post(self):
        """Test case for enterprise_groupon_save_post

        创建团购活动  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
