# coding: utf-8

"""
    企业号意向用户管理

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseLeadsLeadsUser
from models.inline_response2002_data_list import InlineResponse2002DataList  # noqa: E501
from douyin_open.EnterpriseLeadsLeadsUser.rest import ApiException


class TestInlineResponse2002DataList(unittest.TestCase):
    """InlineResponse2002DataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002DataList(self):
        """Test InlineResponse2002DataList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseLeadsLeadsUser.models.inline_response2002_data_list.InlineResponse2002DataList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
