# coding: utf-8

"""
    消息卡片列表

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseImCardCardList
from models.inline_response200_data_cards import InlineResponse200DataCards  # noqa: E501
from douyin_open.EnterpriseImCardCardList.rest import ApiException


class TestInlineResponse200DataCards(unittest.TestCase):
    """InlineResponse200DataCards unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200DataCards(self):
        """Test InlineResponse200DataCards"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseImCardCardList.models.inline_response200_data_cards.InlineResponse200DataCards()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
