# coding: utf-8

"""
    创建消息卡片

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseImCardCardSave
from models.question_list_questions import QuestionListQuestions  # noqa: E501
from douyin_open.EnterpriseImCardCardSave.rest import ApiException


class TestQuestionListQuestions(unittest.TestCase):
    """QuestionListQuestions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuestionListQuestions(self):
        """Test QuestionListQuestions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseImCardCardSave.models.question_list_questions.QuestionListQuestions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
