# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.Oauth2RefreshToken.api.refresh_token_api import RefreshTokenApi  # noqa: E501


class TestRefreshTokenApi(unittest.TestCase):
    """RefreshTokenApi unit test stubs"""

    def setUp(self):
        self.api = RefreshTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_refresh_token_get(self):
        """Test case for oauth_refresh_token_get

        刷新access_token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
