# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.VideoCommentVideoComment
from models.common_response_data import CommonResponseData  # noqa: E501
from douyin_open.VideoCommentVideoComment.rest import ApiException


class TestCommonResponseData(unittest.TestCase):
    """CommonResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonResponseData(self):
        """Test CommonResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.VideoCommentVideoComment.models.common_response_data.CommonResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
