# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ExternalDataUserExternalDataUser
from models.inline_response2005_data import InlineResponse2005Data  # noqa: E501
from douyin_open.ExternalDataUserExternalDataUser.rest import ApiException


class TestInlineResponse2005Data(unittest.TestCase):
    """InlineResponse2005Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2005Data(self):
        """Test InlineResponse2005Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ExternalDataUserExternalDataUser.models.inline_response2005_data.InlineResponse2005Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
