# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.PoiProductProduct.api.poi_spu_api import PoiSpuApi  # noqa: E501


class TestPoiSpuApi(unittest.TestCase):
    """PoiSpuApi unit test stubs"""

    def setUp(self):
        self.api = PoiSpuApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_poi_sku_sync_post(self):
        """Test case for poi_sku_sync_post

        SKU同步  # noqa: E501
        """
        pass

    def test_poi_spu_query_get(self):
        """Test case for poi_spu_query_get

        查询SPU  # noqa: E501
        """
        pass

    def test_poi_spu_sync_post(self):
        """Test case for poi_spu_sync_post

        SPU同步  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
