# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.VideoListVideoList.api.video_list_api import VideoListApi  # noqa: E501


class TestVideoListApi(unittest.TestCase):
    """VideoListApi unit test stubs"""

    def setUp(self):
        self.api = VideoListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_video_list_get(self):
        """Test case for video_list_get

        查询授权账号视频数据  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
