# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.PoiOrderSyncOrderSync.api.poi_order_sync_api import PoiOrderSyncApi  # noqa: E501


class TestPoiOrderSyncApi(unittest.TestCase):
    """PoiOrderSyncApi unit test stubs"""

    def setUp(self):
        self.api = PoiOrderSyncApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_poi_order_sync_post(self):
        """Test case for poi_order_sync_post

        订单同步  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
