# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ExternalDataPoiExternalDataPoi
from models.inline_response2004_data_list import InlineResponse2004DataList  # noqa: E501
from douyin_open.ExternalDataPoiExternalDataPoi.rest import ApiException


class TestInlineResponse2004DataList(unittest.TestCase):
    """InlineResponse2004DataList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004DataList(self):
        """Test InlineResponse2004DataList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ExternalDataPoiExternalDataPoi.models.inline_response2004_data_list.InlineResponse2004DataList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
