# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.ExternalDataPoiExternalDataPoi
from models.external_poi_user import ExternalPoiUser  # noqa: E501
from douyin_open.ExternalDataPoiExternalDataPoi.rest import ApiException


class TestExternalPoiUser(unittest.TestCase):
    """ExternalPoiUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalPoiUser(self):
        """Test ExternalPoiUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.ExternalDataPoiExternalDataPoi.models.external_poi_user.ExternalPoiUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
