# coding: utf-8

"""
    客服会话删除

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterprisePersonaPersonaConvDelete.api.enterprise_im_conversation_delete_api import EnterpriseImConversationDeleteApi  # noqa: E501


class TestEnterpriseImConversationDeleteApi(unittest.TestCase):
    """EnterpriseImConversationDeleteApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseImConversationDeleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_im_persona_conversation_delete_post(self):
        """Test case for enterprise_im_persona_conversation_delete_post

        删除客服会话  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
