# coding: utf-8

"""
    企业号发送消息

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import douyin_open.EnterpriseImEnterpriseIm
from models.fancy_card import FancyCard  # noqa: E501
from douyin_open.EnterpriseImEnterpriseIm.rest import ApiException


class TestFancyCard(unittest.TestCase):
    """FancyCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFancyCard(self):
        """Test FancyCard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = douyin_open.EnterpriseImEnterpriseIm.models.fancy_card.FancyCard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
