# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.StarDataStarData.api.star_hot_list_api import StarHotListApi  # noqa: E501


class TestStarHotListApi(unittest.TestCase):
    """StarHotListApi unit test stubs"""

    def setUp(self):
        self.api = StarHotListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_star_hot_list_get(self):
        """Test case for star_hot_list_get

        获取抖音星图达人热榜  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
