# coding: utf-8

"""
    查看券码状态

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.EnterpriseGrouponGrouponCodeCodeStatus.api.enterprise_groupon_code_status_api import EnterpriseGrouponCodeStatusApi  # noqa: E501


class TestEnterpriseGrouponCodeStatusApi(unittest.TestCase):
    """EnterpriseGrouponCodeStatusApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseGrouponCodeStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enterprise_groupon_code_status_post(self):
        """Test case for enterprise_groupon_code_status_post

        查看券码状态  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
