# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.VideoCommentVideoComment.api.video_comment_api import VideoCommentApi  # noqa: E501


class TestVideoCommentApi(unittest.TestCase):
    """VideoCommentApi unit test stubs"""

    def setUp(self):
        self.api = VideoCommentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_video_comment_list_get(self):
        """Test case for video_comment_list_get

        评论列表  # noqa: E501
        """
        pass

    def test_video_comment_reply_list_get(self):
        """Test case for video_comment_reply_list_get

        评论回复列表  # noqa: E501
        """
        pass

    def test_video_comment_reply_post(self):
        """Test case for video_comment_reply_post

        回复视频评论  # noqa: E501
        """
        pass

    def test_video_comment_top_post(self):
        """Test case for video_comment_top_post

        置顶视频评论(企业号)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
