# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

from douyin_open.DouyinPayDouyinPay.api.douyin_pay_account_trans_api import DouyinPayAccountTransApi  # noqa: E501


class TestDouyinPayAccountTransApi(unittest.TestCase):
    """DouyinPayAccountTransApi unit test stubs"""

    def setUp(self):
        self.api = DouyinPayAccountTransApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_douyin_pay_account_trans_post(self):
        """Test case for douyin_pay_account_trans_post

        商户向用户转账  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
