# coding: utf-8

# flake8: noqa

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from douyin_open.StarAuthorStarAuthor.api.star_author_score_api import StarAuthorScoreApi
# import ApiClient
from douyin_open.StarAuthorStarAuthor.api_client import ApiClient
from douyin_open.StarAuthorStarAuthor.configuration import Configuration
# import models into sdk package
from douyin_open.StarAuthorStarAuthor.models.description import Description
from douyin_open.StarAuthorStarAuthor.models.error_code import ErrorCode
from douyin_open.StarAuthorStarAuthor.models.extra_body import ExtraBody
from douyin_open.StarAuthorStarAuthor.models.inline_response200 import InlineResponse200
from douyin_open.StarAuthorStarAuthor.models.inline_response2001 import InlineResponse2001
from douyin_open.StarAuthorStarAuthor.models.inline_response2001_data import InlineResponse2001Data
from douyin_open.StarAuthorStarAuthor.models.inline_response200_data import InlineResponse200Data
