# coding: utf-8

# flake8: noqa
"""
    客服会话创建

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from douyin_open.EnterprisePersonaPersonaConvCreate.models.body import Body
from douyin_open.EnterprisePersonaPersonaConvCreate.models.description import Description
from douyin_open.EnterprisePersonaPersonaConvCreate.models.error_code import ErrorCode
from douyin_open.EnterprisePersonaPersonaConvCreate.models.extra_body import ExtraBody
from douyin_open.EnterprisePersonaPersonaConvCreate.models.inline_response200 import InlineResponse200
from douyin_open.EnterprisePersonaPersonaConvCreate.models.inline_response200_data import InlineResponse200Data
