# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ExternalItemComment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'str',
        'comment': 'int'
    }

    attribute_map = {
        '_date': 'date',
        'comment': 'comment'
    }

    def __init__(self, _date=None, comment=None):  # noqa: E501
        """ExternalItemComment - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._comment = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if comment is not None:
            self.comment = comment

    @property
    def _date(self):
        """Gets the _date of this ExternalItemComment.  # noqa: E501

        日期  # noqa: E501

        :return: The _date of this ExternalItemComment.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this ExternalItemComment.

        日期  # noqa: E501

        :param _date: The _date of this ExternalItemComment.  # noqa: E501
        :type: str
        """

        self.__date = _date

    @property
    def comment(self):
        """Gets the comment of this ExternalItemComment.  # noqa: E501

        每日评论数  # noqa: E501

        :return: The comment of this ExternalItemComment.  # noqa: E501
        :rtype: int
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this ExternalItemComment.

        每日评论数  # noqa: E501

        :param comment: The comment of this ExternalItemComment.  # noqa: E501
        :type: int
        """

        self._comment = comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalItemComment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalItemComment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
