# coding: utf-8

"""
    客服列表

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Persona(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'persona_id': 'str',
        'nickname': 'str',
        'role_name': 'str'
    }

    attribute_map = {
        'persona_id': 'persona_id',
        'nickname': 'nickname',
        'role_name': 'role_name'
    }

    def __init__(self, persona_id=None, nickname=None, role_name=None):  # noqa: E501
        """Persona - a model defined in Swagger"""  # noqa: E501
        self._persona_id = None
        self._nickname = None
        self._role_name = None
        self.discriminator = None
        self.persona_id = persona_id
        self.nickname = nickname
        if role_name is not None:
            self.role_name = role_name

    @property
    def persona_id(self):
        """Gets the persona_id of this Persona.  # noqa: E501

        客服id  # noqa: E501

        :return: The persona_id of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._persona_id

    @persona_id.setter
    def persona_id(self, persona_id):
        """Sets the persona_id of this Persona.

        客服id  # noqa: E501

        :param persona_id: The persona_id of this Persona.  # noqa: E501
        :type: str
        """
        if persona_id is None:
            raise ValueError("Invalid value for `persona_id`, must not be `None`")  # noqa: E501

        self._persona_id = persona_id

    @property
    def nickname(self):
        """Gets the nickname of this Persona.  # noqa: E501

        客服昵称  # noqa: E501

        :return: The nickname of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this Persona.

        客服昵称  # noqa: E501

        :param nickname: The nickname of this Persona.  # noqa: E501
        :type: str
        """
        if nickname is None:
            raise ValueError("Invalid value for `nickname`, must not be `None`")  # noqa: E501

        self._nickname = nickname

    @property
    def role_name(self):
        """Gets the role_name of this Persona.  # noqa: E501

        角色名（暂未开放）  # noqa: E501

        :return: The role_name of this Persona.  # noqa: E501
        :rtype: str
        """
        return self._role_name

    @role_name.setter
    def role_name(self, role_name):
        """Sets the role_name of this Persona.

        角色名（暂未开放）  # noqa: E501

        :param role_name: The role_name of this Persona.  # noqa: E501
        :type: str
        """

        self._role_name = role_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Persona, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Persona):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
