# coding: utf-8

# flake8: noqa
"""

    关注指定抖音号  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from douyin_open.RelationRelationFollow.models.common_response import CommonResponse
from douyin_open.RelationRelationFollow.models.common_response_data import CommonResponseData
from douyin_open.RelationRelationFollow.models.description import Description
from douyin_open.RelationRelationFollow.models.error_code import ErrorCode
from douyin_open.RelationRelationFollow.models.extra_body import ExtraBody
