# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ExternalPoiBillboard(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'poi_id': 'str',
        'poi_name': 'str',
        'score': 'str',
        'rank': 'int'
    }

    attribute_map = {
        'poi_id': 'poi_id',
        'poi_name': 'poi_name',
        'score': 'score',
        'rank': 'rank'
    }

    def __init__(self, poi_id=None, poi_name=None, score=None, rank=None):  # noqa: E501
        """ExternalPoiBillboard - a model defined in Swagger"""  # noqa: E501
        self._poi_id = None
        self._poi_name = None
        self._score = None
        self._rank = None
        self.discriminator = None
        if poi_id is not None:
            self.poi_id = poi_id
        if poi_name is not None:
            self.poi_name = poi_name
        if score is not None:
            self.score = score
        if rank is not None:
            self.rank = rank

    @property
    def poi_id(self):
        """Gets the poi_id of this ExternalPoiBillboard.  # noqa: E501

        poi id  # noqa: E501

        :return: The poi_id of this ExternalPoiBillboard.  # noqa: E501
        :rtype: str
        """
        return self._poi_id

    @poi_id.setter
    def poi_id(self, poi_id):
        """Sets the poi_id of this ExternalPoiBillboard.

        poi id  # noqa: E501

        :param poi_id: The poi_id of this ExternalPoiBillboard.  # noqa: E501
        :type: str
        """

        self._poi_id = poi_id

    @property
    def poi_name(self):
        """Gets the poi_name of this ExternalPoiBillboard.  # noqa: E501

        poi名称  # noqa: E501

        :return: The poi_name of this ExternalPoiBillboard.  # noqa: E501
        :rtype: str
        """
        return self._poi_name

    @poi_name.setter
    def poi_name(self, poi_name):
        """Sets the poi_name of this ExternalPoiBillboard.

        poi名称  # noqa: E501

        :param poi_name: The poi_name of this ExternalPoiBillboard.  # noqa: E501
        :type: str
        """

        self._poi_name = poi_name

    @property
    def score(self):
        """Gets the score of this ExternalPoiBillboard.  # noqa: E501

        得分  # noqa: E501

        :return: The score of this ExternalPoiBillboard.  # noqa: E501
        :rtype: str
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ExternalPoiBillboard.

        得分  # noqa: E501

        :param score: The score of this ExternalPoiBillboard.  # noqa: E501
        :type: str
        """

        self._score = score

    @property
    def rank(self):
        """Gets the rank of this ExternalPoiBillboard.  # noqa: E501

        排名  # noqa: E501

        :return: The rank of this ExternalPoiBillboard.  # noqa: E501
        :rtype: int
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this ExternalPoiBillboard.

        排名  # noqa: E501

        :param rank: The rank of this ExternalPoiBillboard.  # noqa: E501
        :type: int
        """

        self._rank = rank

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalPoiBillboard, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalPoiBillboard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
