# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse2001Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'ErrorCode',
        'description': 'Description',
        'gender_list': 'list[ExternalPoiUser]',
        'age_list': 'list[ExternalPoiUser]',
        'city_list': 'list[ExternalPoiUser]'
    }

    attribute_map = {
        'error_code': 'error_code',
        'description': 'description',
        'gender_list': 'gender_list',
        'age_list': 'age_list',
        'city_list': 'city_list'
    }

    def __init__(self, error_code=None, description=None, gender_list=None, age_list=None, city_list=None):  # noqa: E501
        """InlineResponse2001Data - a model defined in Swagger"""  # noqa: E501
        self._error_code = None
        self._description = None
        self._gender_list = None
        self._age_list = None
        self._city_list = None
        self.discriminator = None
        self.error_code = error_code
        self.description = description
        if gender_list is not None:
            self.gender_list = gender_list
        if age_list is not None:
            self.age_list = age_list
        if city_list is not None:
            self.city_list = city_list

    @property
    def error_code(self):
        """Gets the error_code of this InlineResponse2001Data.  # noqa: E501


        :return: The error_code of this InlineResponse2001Data.  # noqa: E501
        :rtype: ErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this InlineResponse2001Data.


        :param error_code: The error_code of this InlineResponse2001Data.  # noqa: E501
        :type: ErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def description(self):
        """Gets the description of this InlineResponse2001Data.  # noqa: E501


        :return: The description of this InlineResponse2001Data.  # noqa: E501
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse2001Data.


        :param description: The description of this InlineResponse2001Data.  # noqa: E501
        :type: Description
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def gender_list(self):
        """Gets the gender_list of this InlineResponse2001Data.  # noqa: E501


        :return: The gender_list of this InlineResponse2001Data.  # noqa: E501
        :rtype: list[ExternalPoiUser]
        """
        return self._gender_list

    @gender_list.setter
    def gender_list(self, gender_list):
        """Sets the gender_list of this InlineResponse2001Data.


        :param gender_list: The gender_list of this InlineResponse2001Data.  # noqa: E501
        :type: list[ExternalPoiUser]
        """

        self._gender_list = gender_list

    @property
    def age_list(self):
        """Gets the age_list of this InlineResponse2001Data.  # noqa: E501


        :return: The age_list of this InlineResponse2001Data.  # noqa: E501
        :rtype: list[ExternalPoiUser]
        """
        return self._age_list

    @age_list.setter
    def age_list(self, age_list):
        """Sets the age_list of this InlineResponse2001Data.


        :param age_list: The age_list of this InlineResponse2001Data.  # noqa: E501
        :type: list[ExternalPoiUser]
        """

        self._age_list = age_list

    @property
    def city_list(self):
        """Gets the city_list of this InlineResponse2001Data.  # noqa: E501


        :return: The city_list of this InlineResponse2001Data.  # noqa: E501
        :rtype: list[ExternalPoiUser]
        """
        return self._city_list

    @city_list.setter
    def city_list(self, city_list):
        """Sets the city_list of this InlineResponse2001Data.


        :param city_list: The city_list of this InlineResponse2001Data.  # noqa: E501
        :type: list[ExternalPoiUser]
        """

        self._city_list = city_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
