# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse2004DataList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'poi_id': 'str',
        'name': 'str',
        'address': 'str'
    }

    attribute_map = {
        'poi_id': 'poi_id',
        'name': 'name',
        'address': 'address'
    }

    def __init__(self, poi_id=None, name=None, address=None):  # noqa: E501
        """InlineResponse2004DataList - a model defined in Swagger"""  # noqa: E501
        self._poi_id = None
        self._name = None
        self._address = None
        self.discriminator = None
        if poi_id is not None:
            self.poi_id = poi_id
        if name is not None:
            self.name = name
        if address is not None:
            self.address = address

    @property
    def poi_id(self):
        """Gets the poi_id of this InlineResponse2004DataList.  # noqa: E501

        poi的Id  # noqa: E501

        :return: The poi_id of this InlineResponse2004DataList.  # noqa: E501
        :rtype: str
        """
        return self._poi_id

    @poi_id.setter
    def poi_id(self, poi_id):
        """Sets the poi_id of this InlineResponse2004DataList.

        poi的Id  # noqa: E501

        :param poi_id: The poi_id of this InlineResponse2004DataList.  # noqa: E501
        :type: str
        """

        self._poi_id = poi_id

    @property
    def name(self):
        """Gets the name of this InlineResponse2004DataList.  # noqa: E501

        poi名称  # noqa: E501

        :return: The name of this InlineResponse2004DataList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2004DataList.

        poi名称  # noqa: E501

        :param name: The name of this InlineResponse2004DataList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address(self):
        """Gets the address of this InlineResponse2004DataList.  # noqa: E501

        地址详情  # noqa: E501

        :return: The address of this InlineResponse2004DataList.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this InlineResponse2004DataList.

        地址详情  # noqa: E501

        :param address: The address of this InlineResponse2004DataList.  # noqa: E501
        :type: str
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2004DataList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004DataList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
