# coding: utf-8

# flake8: noqa
"""
    团购活动详情

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.description import Description
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.error_code import ErrorCode
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.extra_body import ExtraBody
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.groupon_item import GrouponItem
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.groupon_item_groupon_goods import GrouponItemGrouponGoods
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.inline_response200 import InlineResponse200
from douyin_open.EnterpriseGrouponGrouponGrouponDetail.models.inline_response200_data import InlineResponse200Data
