# coding: utf-8

"""
    团购活动事件回调

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CustomCodeFetchContent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'groupon_id': 'str',
        'quantity': 'int',
        'fetch_seq': 'str'
    }

    attribute_map = {
        'groupon_id': 'groupon_id',
        'quantity': 'quantity',
        'fetch_seq': 'fetch_seq'
    }

    def __init__(self, groupon_id=None, quantity=None, fetch_seq=None):  # noqa: E501
        """CustomCodeFetchContent - a model defined in Swagger"""  # noqa: E501
        self._groupon_id = None
        self._quantity = None
        self._fetch_seq = None
        self.discriminator = None
        if groupon_id is not None:
            self.groupon_id = groupon_id
        if quantity is not None:
            self.quantity = quantity
        if fetch_seq is not None:
            self.fetch_seq = fetch_seq

    @property
    def groupon_id(self):
        """Gets the groupon_id of this CustomCodeFetchContent.  # noqa: E501

        团购活动的ID  # noqa: E501

        :return: The groupon_id of this CustomCodeFetchContent.  # noqa: E501
        :rtype: str
        """
        return self._groupon_id

    @groupon_id.setter
    def groupon_id(self, groupon_id):
        """Sets the groupon_id of this CustomCodeFetchContent.

        团购活动的ID  # noqa: E501

        :param groupon_id: The groupon_id of this CustomCodeFetchContent.  # noqa: E501
        :type: str
        """

        self._groupon_id = groupon_id

    @property
    def quantity(self):
        """Gets the quantity of this CustomCodeFetchContent.  # noqa: E501

        需要的券码数量  # noqa: E501

        :return: The quantity of this CustomCodeFetchContent.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this CustomCodeFetchContent.

        需要的券码数量  # noqa: E501

        :param quantity: The quantity of this CustomCodeFetchContent.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def fetch_seq(self):
        """Gets the fetch_seq of this CustomCodeFetchContent.  # noqa: E501

        同个sequence 结果幂等  # noqa: E501

        :return: The fetch_seq of this CustomCodeFetchContent.  # noqa: E501
        :rtype: str
        """
        return self._fetch_seq

    @fetch_seq.setter
    def fetch_seq(self, fetch_seq):
        """Sets the fetch_seq of this CustomCodeFetchContent.

        同个sequence 结果幂等  # noqa: E501

        :param fetch_seq: The fetch_seq of this CustomCodeFetchContent.  # noqa: E501
        :type: str
        """

        self._fetch_seq = fetch_seq

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomCodeFetchContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomCodeFetchContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
