# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MatchOriginData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supplier_ext_id': 'str',
        'amap_id': 'str',
        'poi_name': 'str',
        'province': 'str',
        'city': 'str',
        'address': 'str',
        'latitude': 'float',
        'longitude': 'float'
    }

    attribute_map = {
        'supplier_ext_id': 'supplier_ext_id',
        'amap_id': 'amap_id',
        'poi_name': 'poi_name',
        'province': 'province',
        'city': 'city',
        'address': 'address',
        'latitude': 'latitude',
        'longitude': 'longitude'
    }

    def __init__(self, supplier_ext_id=None, amap_id=None, poi_name=None, province=None, city=None, address=None, latitude=None, longitude=None):  # noqa: E501
        """MatchOriginData - a model defined in Swagger"""  # noqa: E501
        self._supplier_ext_id = None
        self._amap_id = None
        self._poi_name = None
        self._province = None
        self._city = None
        self._address = None
        self._latitude = None
        self._longitude = None
        self.discriminator = None
        self.supplier_ext_id = supplier_ext_id
        if amap_id is not None:
            self.amap_id = amap_id
        self.poi_name = poi_name
        self.province = province
        self.city = city
        self.address = address
        self.latitude = latitude
        self.longitude = longitude

    @property
    def supplier_ext_id(self):
        """Gets the supplier_ext_id of this MatchOriginData.  # noqa: E501

        第三方商户ID  # noqa: E501

        :return: The supplier_ext_id of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._supplier_ext_id

    @supplier_ext_id.setter
    def supplier_ext_id(self, supplier_ext_id):
        """Sets the supplier_ext_id of this MatchOriginData.

        第三方商户ID  # noqa: E501

        :param supplier_ext_id: The supplier_ext_id of this MatchOriginData.  # noqa: E501
        :type: str
        """
        if supplier_ext_id is None:
            raise ValueError("Invalid value for `supplier_ext_id`, must not be `None`")  # noqa: E501

        self._supplier_ext_id = supplier_ext_id

    @property
    def amap_id(self):
        """Gets the amap_id of this MatchOriginData.  # noqa: E501

        高德POI ID  # noqa: E501

        :return: The amap_id of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._amap_id

    @amap_id.setter
    def amap_id(self, amap_id):
        """Sets the amap_id of this MatchOriginData.

        高德POI ID  # noqa: E501

        :param amap_id: The amap_id of this MatchOriginData.  # noqa: E501
        :type: str
        """

        self._amap_id = amap_id

    @property
    def poi_name(self):
        """Gets the poi_name of this MatchOriginData.  # noqa: E501

        POI名称  # noqa: E501

        :return: The poi_name of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._poi_name

    @poi_name.setter
    def poi_name(self, poi_name):
        """Sets the poi_name of this MatchOriginData.

        POI名称  # noqa: E501

        :param poi_name: The poi_name of this MatchOriginData.  # noqa: E501
        :type: str
        """
        if poi_name is None:
            raise ValueError("Invalid value for `poi_name`, must not be `None`")  # noqa: E501

        self._poi_name = poi_name

    @property
    def province(self):
        """Gets the province of this MatchOriginData.  # noqa: E501

        POI所在省份  # noqa: E501

        :return: The province of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._province

    @province.setter
    def province(self, province):
        """Sets the province of this MatchOriginData.

        POI所在省份  # noqa: E501

        :param province: The province of this MatchOriginData.  # noqa: E501
        :type: str
        """
        if province is None:
            raise ValueError("Invalid value for `province`, must not be `None`")  # noqa: E501

        self._province = province

    @property
    def city(self):
        """Gets the city of this MatchOriginData.  # noqa: E501

        POI所在城市  # noqa: E501

        :return: The city of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this MatchOriginData.

        POI所在城市  # noqa: E501

        :param city: The city of this MatchOriginData.  # noqa: E501
        :type: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def address(self):
        """Gets the address of this MatchOriginData.  # noqa: E501

        POI地址  # noqa: E501

        :return: The address of this MatchOriginData.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this MatchOriginData.

        POI地址  # noqa: E501

        :param address: The address of this MatchOriginData.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def latitude(self):
        """Gets the latitude of this MatchOriginData.  # noqa: E501

        纬度  # noqa: E501

        :return: The latitude of this MatchOriginData.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this MatchOriginData.

        纬度  # noqa: E501

        :param latitude: The latitude of this MatchOriginData.  # noqa: E501
        :type: float
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this MatchOriginData.  # noqa: E501

        经度  # noqa: E501

        :return: The longitude of this MatchOriginData.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this MatchOriginData.

        经度  # noqa: E501

        :param longitude: The longitude of this MatchOriginData.  # noqa: E501
        :type: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchOriginData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchOriginData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
