# coding: utf-8

# flake8: noqa

"""

    仅对内提供  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from douyin_open.MusicCollectionListMusicCollectionList.api.music_collection_api import MusicCollectionApi
# import ApiClient
from douyin_open.MusicCollectionListMusicCollectionList.api_client import ApiClient
from douyin_open.MusicCollectionListMusicCollectionList.configuration import Configuration
# import models into sdk package
from douyin_open.MusicCollectionListMusicCollectionList.models.cursor import Cursor
from douyin_open.MusicCollectionListMusicCollectionList.models.description import Description
from douyin_open.MusicCollectionListMusicCollectionList.models.error_code import ErrorCode
from douyin_open.MusicCollectionListMusicCollectionList.models.extra_body import ExtraBody
from douyin_open.MusicCollectionListMusicCollectionList.models.has_more import HasMore
from douyin_open.MusicCollectionListMusicCollectionList.models.img_url import ImgUrl
from douyin_open.MusicCollectionListMusicCollectionList.models.inline_response200 import InlineResponse200
from douyin_open.MusicCollectionListMusicCollectionList.models.inline_response200_data import InlineResponse200Data
from douyin_open.MusicCollectionListMusicCollectionList.models.inline_response200_data_list import InlineResponse200DataList
